"use client";

import React from 'react';
import CPaaSExplainer from '@/components/marketing/CPaaSExplainer';
import ChatbotWithLeadGen from '@/components/chatbot/ChatbotWithLeadGen';
import { Button } from '@/components/ui/button';
import { ArrowRight } from 'lucide-react';

export default function CPaaSPage() {
  return (
    <div className="min-h-screen bg-slate-900 text-white">
      {/* Header */}
      <header className="bg-slate-800 border-b border-slate-700">
        <div className="container mx-auto py-4 px-4 flex justify-between items-center">
          <div className="flex items-center">
            <h1 className="text-xl font-bold text-white">Ron AI</h1>
          </div>
          <nav>
            <ul className="flex space-x-6">
              <li><a href="/" className="text-slate-300 hover:text-white transition-colors">Home</a></li>
              <li><a href="/cpaas" className="text-blue-400 hover:text-blue-300 transition-colors font-medium">CPaaS</a></li>
              <li><a href="#" className="text-slate-300 hover:text-white transition-colors">Features</a></li>
              <li><a href="#" className="text-slate-300 hover:text-white transition-colors">Pricing</a></li>
              <li><a href="#" className="text-slate-300 hover:text-white transition-colors">About</a></li>
            </ul>
          </nav>
          <div>
            <Button
              className="bg-blue-600 hover:bg-blue-700 text-white"
            >
              Request Demo
            </Button>
          </div>
        </div>
      </header>
      
      {/* Main Content */}
      <main>
        {/* CPaaS Explainer Component */}
        <CPaaSExplainer />
        
        {/* Case Study Section */}
        <section className="py-16 px-4 bg-gradient-to-br from-slate-900 to-slate-800">
          <div className="max-w-6xl mx-auto">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold mb-4">Success Stories</h2>
              <p className="text-xl text-slate-300 max-w-3xl mx-auto">
                See how healthcare organizations are transforming care planning with Ron AI's CPaaS.
              </p>
            </div>
            
            <div className="grid md:grid-cols-2 gap-8">
              <div className="bg-slate-800 border border-slate-700 rounded-xl overflow-hidden shadow-xl">
                <div className="h-48 bg-gradient-to-r from-blue-900 to-indigo-900 flex items-center justify-center">
                  <h3 className="text-2xl font-bold">Memorial Healthcare System</h3>
                </div>
                <div className="p-6">
                  <p className="text-slate-300 mb-4">
                    "Ron AI's CPaaS platform reduced our care planning time by 87% while improving documentation quality and standardization across our network of 6 hospitals."
                  </p>
                  <p className="text-slate-400 italic">- Sarah Johnson, CNO</p>
                  <div className="mt-6">
                    <p className="text-slate-200 font-medium">Results:</p>
                    <ul className="mt-2 space-y-2 text-slate-300">
                      <li className="flex items-center">
                        <span className="h-2 w-2 bg-green-500 rounded-full mr-2"></span>
                        87% reduction in documentation time
                      </li>
                      <li className="flex items-center">
                        <span className="h-2 w-2 bg-green-500 rounded-full mr-2"></span>
                        34% improvement in care plan quality scores
                      </li>
                      <li className="flex items-center">
                        <span className="h-2 w-2 bg-green-500 rounded-full mr-2"></span>
                        $2.3M annual savings in staff time
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              
              <div className="bg-slate-800 border border-slate-700 rounded-xl overflow-hidden shadow-xl">
                <div className="h-48 bg-gradient-to-r from-purple-900 to-blue-900 flex items-center justify-center">
                  <h3 className="text-2xl font-bold">University Health Partners</h3>
                </div>
                <div className="p-6">
                  <p className="text-slate-300 mb-4">
                    "The comprehensive care plans generated by Ron AI have significantly improved our standardization while allowing for personalization. Our nursing staff can focus more on patient care."
                  </p>
                  <p className="text-slate-400 italic">- Michael Torres, Director of Nursing Informatics</p>
                  <div className="mt-6">
                    <p className="text-slate-200 font-medium">Results:</p>
                    <ul className="mt-2 space-y-2 text-slate-300">
                      <li className="flex items-center">
                        <span className="h-2 w-2 bg-green-500 rounded-full mr-2"></span>
                        92% of nurses report improved job satisfaction
                      </li>
                      <li className="flex items-center">
                        <span className="h-2 w-2 bg-green-500 rounded-full mr-2"></span>
                        28% reduction in care planning variations
                      </li>
                      <li className="flex items-center">
                        <span className="h-2 w-2 bg-green-500 rounded-full mr-2"></span>
                        41% increase in documented interventions
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            
            <div className="text-center mt-12">
              <Button
                className="bg-transparent border border-blue-500 text-blue-400 hover:bg-blue-900/20"
              >
                View More Case Studies <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </div>
          </div>
        </section>
      </main>
      
      {/* Footer */}
      <footer className="bg-slate-800 border-t border-slate-700 py-12 px-4">
        <div className="max-w-6xl mx-auto">
          <div className="grid md:grid-cols-4 gap-8">
            <div>
              <h3 className="font-bold text-lg mb-4">Ron AI</h3>
              <p className="text-slate-400 text-sm">
                Transforming healthcare with AI-powered care planning solutions.
              </p>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Products</h4>
              <ul className="space-y-2 text-sm text-slate-400">
                <li><a href="#" className="hover:text-white transition-colors">CPaaS Platform</a></li>
                <li><a href="#" className="hover:text-white transition-colors">EHR Integrations</a></li>
                <li><a href="#" className="hover:text-white transition-colors">Analytics Dashboard</a></li>
                <li><a href="#" className="hover:text-white transition-colors">Mobile App</a></li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Resources</h4>
              <ul className="space-y-2 text-sm text-slate-400">
                <li><a href="#" className="hover:text-white transition-colors">Documentation</a></li>
                <li><a href="#" className="hover:text-white transition-colors">API Reference</a></li>
                <li><a href="#" className="hover:text-white transition-colors">Blog</a></li>
                <li><a href="#" className="hover:text-white transition-colors">Case Studies</a></li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Company</h4>
              <ul className="space-y-2 text-sm text-slate-400">
                <li><a href="#" className="hover:text-white transition-colors">About Us</a></li>
                <li><a href="#" className="hover:text-white transition-colors">Careers</a></li>
                <li><a href="#" className="hover:text-white transition-colors">Contact</a></li>
                <li><a href="#" className="hover:text-white transition-colors">Privacy Policy</a></li>
              </ul>
            </div>
          </div>
          <div className="mt-12 pt-6 border-t border-slate-700 text-center text-sm text-slate-500">
            &copy; {new Date().getFullYear()} Ron AI. All rights reserved.
          </div>
        </div>
      </footer>
      
      {/* Chatbot Component that uses existing Gemini implementation */}
      <ChatbotWithLeadGen />
    </div>
  );
}