/*
  Scenario Library
  20 pre-defined patient scenarios: 10 mental-health cases and 10 medical-surgical cases.
  Each object follows the FormState schema used in PatientDataForm.
*/

export interface VitalSigns {
  vital_bp: string;
  vital_pulse: string;
  vital_resp_rate: string;
  vital_temp: string;
  vital_o2sat: string;
  vital_pain_score: string;
}

export interface FormState {
  patient_full_name: string;
  patient_age: string;
  patient_gender: string;
  patient_mrn: string;
  patient_dob: string;
  patient_insurance_plan: string;
  patient_policy_number: string;
  patient_primary_provider: string;
  patient_admission_date: string;
  allergies: string[];
  vitalSigns: VitalSigns;
  nyha_class_description: string;
  primary_diagnosis_text: string;
  secondaryDiagnoses: string[];
  labs: any[];
  medications: any[];
  treatments: any[];
  last_imaging_summary: string;
  last_ecg_summary: string;
}

export interface PatientScenario {
  name: string;
  description: string;
  data: FormState;
}

// Helper to generate blank vitals
const blankVitals: VitalSigns = {
  vital_bp: "120/80",
  vital_pulse: "80",
  vital_resp_rate: "16",
  vital_temp: "98.6",
  vital_o2sat: "98%",
  vital_pain_score: "0",
};

// ---------- Mental-Health Scenarios (10) ----------
const mentalHealth: PatientScenario[] = [
  {
    name: "Bipolar I – Acute Mania",
    description: "30-year-old male in acute manic episode requiring stabilization.",
    data: {
      patient_full_name: "Brian Lee",
      patient_age: "30",
      patient_gender: "Male",
      patient_mrn: "MH001",
      patient_dob: "1995-06-12",
      patient_insurance_plan: "Aetna",
      patient_policy_number: "AET-MH001",
      patient_primary_provider: "Dr. Patel",
      patient_admission_date: "2025-05-08",
      allergies: [],
      vitalSigns: blankVitals,
      nyha_class_description: "",
      primary_diagnosis_text: "Bipolar I, manic, severe",
      secondaryDiagnoses: [],
      labs: [],
      medications: [],
      treatments: [],
      last_imaging_summary: "",
      last_ecg_summary: "",
    },
  },
  {
    name: "Schizophrenia – Paranoid Type",
    description: "22-year-old female with acute exacerbation of hallucinations.",
    data: {
      patient_full_name: "Clara Jones",
      patient_age: "22",
      patient_gender: "Female",
      patient_mrn: "MH002",
      patient_dob: "2003-01-17",
      patient_insurance_plan: "Medicaid",
      patient_policy_number: "MED-MH002",
      patient_primary_provider: "Dr. Yang",
      patient_admission_date: "2025-05-07",
      allergies: ["Penicillin"],
      vitalSigns: blankVitals,
      nyha_class_description: "",
      primary_diagnosis_text: "Paranoid schizophrenia – acute exacerbation",
      secondaryDiagnoses: [],
      labs: [],
      medications: [],
      treatments: [],
      last_imaging_summary: "",
      last_ecg_summary: "",
    },
  },
  {
    name: "PTSD – Combat Veteran",
    description: "34-year-old male veteran with intrusive memories and hypervigilance.",
    data: {
      patient_full_name: "Evan Rivera",
      patient_age: "34",
      patient_gender: "Male",
      patient_mrn: "MH003",
      patient_dob: "1991-04-11",
      patient_insurance_plan: "VA",
      patient_policy_number: "VA-MH003",
      patient_primary_provider: "Dr. Lopez",
      patient_admission_date: "2025-05-06",
      allergies: [],
      vitalSigns: blankVitals,
      nyha_class_description: "",
      primary_diagnosis_text: "Chronic PTSD",
      secondaryDiagnoses: ["Alcohol Use Disorder"],
      labs: [],
      medications: [],
      treatments: [],
      last_imaging_summary: "",
      last_ecg_summary: "",
    },
  },
  {
    name: "OCD – Contamination Type",
    description: "26-year-old female with severe compulsive hand-washing.",
    data: {
      patient_full_name: "Grace Hall",
      patient_age: "26",
      patient_gender: "Female",
      patient_mrn: "MH004",
      patient_dob: "1999-12-05",
      patient_insurance_plan: "Cigna",
      patient_policy_number: "CIG-MH004",
      patient_primary_provider: "Dr. Brown",
      patient_admission_date: "2025-05-05",
      allergies: [],
      vitalSigns: blankVitals,
      nyha_class_description: "",
      primary_diagnosis_text: "Obsessive-Compulsive Disorder, severe",
      secondaryDiagnoses: [],
      labs: [],
      medications: [],
      treatments: [],
      last_imaging_summary: "",
      last_ecg_summary: "",
    },
  },
  {
    name: "Generalized Anxiety Disorder – Moderate",
    description: "28-year-old male with excessive worry and insomnia.",
    data: {
      patient_full_name: "David Kim",
      patient_age: "28",
      patient_gender: "Male",
      patient_mrn: "MH005",
      patient_dob: "1997-09-20",
      patient_insurance_plan: "UHC",
      patient_policy_number: "UHC-MH005",
      patient_primary_provider: "Dr. Singh",
      patient_admission_date: "2025-05-04",
      allergies: [],
      vitalSigns: blankVitals,
      nyha_class_description: "",
      primary_diagnosis_text: "Generalized Anxiety Disorder",
      secondaryDiagnoses: ["Insomnia"],
      labs: [],
      medications: [],
      treatments: [],
      last_imaging_summary: "",
      last_ecg_summary: "",
    },
  },
  {
    name: "Panic Disorder – Acute",
    description: "29-year-old female with sudden chest tightness and fear of dying.",
    data: {
      patient_full_name: "Hannah Moore",
      patient_age: "29",
      patient_gender: "Female",
      patient_mrn: "MH006",
      patient_dob: "1996-03-14",
      patient_insurance_plan: "BCBS",
      patient_policy_number: "BCBS-MH006",
      patient_primary_provider: "Dr. Green",
      patient_admission_date: "2025-05-09",
      allergies: ["Sulfa"],
      vitalSigns: blankVitals,
      nyha_class_description: "",
      primary_diagnosis_text: "Panic Disorder",
      secondaryDiagnoses: [],
      labs: [],
      medications: [],
      treatments: [],
      last_imaging_summary: "",
      last_ecg_summary: "",
    },
  },
  {
    name: "Borderline Personality Disorder – Crisis",
    description: "24-year-old female with self-injurious behavior post conflict.",
    data: {
      patient_full_name: "Isabella Nguyen",
      patient_age: "24",
      patient_gender: "Female",
      patient_mrn: "MH007",
      patient_dob: "2001-07-01",
      patient_insurance_plan: "Medicaid",
      patient_policy_number: "MED-MH007",
      patient_primary_provider: "Dr. Patel",
      patient_admission_date: "2025-05-03",
      allergies: [],
      vitalSigns: blankVitals,
      nyha_class_description: "",
      primary_diagnosis_text: "Borderline Personality Disorder",
      secondaryDiagnoses: ["Depressive Disorder"],
      labs: [],
      medications: [],
      treatments: [],
      last_imaging_summary: "",
      last_ecg_summary: "",
    },
  },
  {
    name: "Alcohol Withdrawal – Moderate",
    description: "48-year-old male with tremors and anxiety after cessation.",
    data: {
      patient_full_name: "Jacob Scott",
      patient_age: "48",
      patient_gender: "Male",
      patient_mrn: "MH008",
      patient_dob: "1977-01-30",
      patient_insurance_plan: "Humana",
      patient_policy_number: "HUM-MH008",
      patient_primary_provider: "Dr. Stone",
      patient_admission_date: "2025-05-04",
      allergies: [],
      vitalSigns: blankVitals,
      nyha_class_description: "",
      primary_diagnosis_text: "Alcohol Withdrawal",
      secondaryDiagnoses: [],
      labs: [],
      medications: [],
      treatments: [],
      last_imaging_summary: "",
      last_ecg_summary: "",
    },
  },
  {
    name: "ADHD – Predominantly Inattentive",
    description: "35-year-old male with chronic inattentiveness at work.",
    data: {
      patient_full_name: "Kyle Turner",
      patient_age: "35",
      patient_gender: "Male",
      patient_mrn: "MH009",
      patient_dob: "1990-10-10",
      patient_insurance_plan: "BCBS",
      patient_policy_number: "BCBS-MH009",
      patient_primary_provider: "Dr. Young",
      patient_admission_date: "2025-05-05",
      allergies: [],
      vitalSigns: blankVitals,
      nyha_class_description: "",
      primary_diagnosis_text: "ADHD – inattentive type",
      secondaryDiagnoses: [],
      labs: [],
      medications: [],
      treatments: [],
      last_imaging_summary: "",
      last_ecg_summary: "",
    },
  },
  {
    name: "Anorexia Nervosa – Restricting Type",
    description: "19-year-old female BMI 16 with amenorrhea.",
    data: {
      patient_full_name: "Lily Adams",
      patient_age: "19",
      patient_gender: "Female",
      patient_mrn: "MH010",
      patient_dob: "2006-02-02",
      patient_insurance_plan: "Student Health",
      patient_policy_number: "STU-MH010",
      patient_primary_provider: "Dr. Rivera",
      patient_admission_date: "2025-05-06",
      allergies: [],
      vitalSigns: { ...blankVitals, vital_bp: "90/58", vital_pulse: "50" },
      nyha_class_description: "",
      primary_diagnosis_text: "Anorexia Nervosa",
      secondaryDiagnoses: ["Osteopenia"],
      labs: [],
      medications: [],
      treatments: [],
      last_imaging_summary: "",
      last_ecg_summary: "Sinus bradycardia",
    },
  },
];

// ---------- Medical-Surgical Scenarios (10) ----------
const medical: PatientScenario[] = [
  {
    name: "CHF Exacerbation – NYHA III",
    description: "68-year-old male with systolic heart failure and weight gain.",
    data: {
      patient_full_name: "Larry Baker",
      patient_age: "68",
      patient_gender: "Male",
      patient_mrn: "MED001",
      patient_dob: "1957-05-08",
      patient_insurance_plan: "Medicare",
      patient_policy_number: "MED-001",
      patient_primary_provider: "Dr. Clark",
      patient_admission_date: "2025-05-02",
      allergies: ["Aspirin"],
      vitalSigns: blankVitals,
      nyha_class_description: "III",
      primary_diagnosis_text: "CHF exacerbation",
      secondaryDiagnoses: ["Hypertension"],
      labs: [],
      medications: [],
      treatments: [],
      last_imaging_summary: "",
      last_ecg_summary: "",
    },
  },
  {
    name: "COPD Exacerbation – Moderate",
    description: "72-year-old female with increased dyspnea and sputum.",
    data: {
      patient_full_name: "Mary Johnson",
      patient_age: "72",
      patient_gender: "Female",
      patient_mrn: "MED002",
      patient_dob: "1953-03-22",
      patient_insurance_plan: "Medicare",
      patient_policy_number: "MED-002",
      patient_primary_provider: "Dr. Chen",
      patient_admission_date: "2025-05-01",
      allergies: ["Codeine"],
      vitalSigns: blankVitals,
      nyha_class_description: "",
      primary_diagnosis_text: "COPD exacerbation",
      secondaryDiagnoses: [],
      labs: [],
      medications: [],
      treatments: [],
      last_imaging_summary: "",
      last_ecg_summary: "",
    },
  },
  {
    name: "Diabetic Ketoacidosis – Type 1",
    description: "22-year-old female with polyuria and abdominal pain.",
    data: {
      patient_full_name: "Natalie Price",
      patient_age: "22",
      patient_gender: "Female",
      patient_mrn: "MED003",
      patient_dob: "2003-09-01",
      patient_insurance_plan: "Cigna",
      patient_policy_number: "MED-003",
      patient_primary_provider: "Dr. Ahmed",
      patient_admission_date: "2025-05-03",
      allergies: [],
      vitalSigns: blankVitals,
      nyha_class_description: "",
      primary_diagnosis_text: "Diabetic Ketoacidosis",
      secondaryDiagnoses: [],
      labs: [],
      medications: [],
      treatments: [],
      last_imaging_summary: "",
      last_ecg_summary: "",
    },
  },
  {
    name: "STEMI – Post PCI",
    description: "60-year-old male day 1 post LAD stent.",
    data: {
      patient_full_name: "Oscar Diaz",
      patient_age: "60",
      patient_gender: "Male",
      patient_mrn: "MED004",
      patient_dob: "1965-11-12",
      patient_insurance_plan: "Humana",
      patient_policy_number: "MED-004",
      patient_primary_provider: "Dr. Roberts",
      patient_admission_date: "2025-05-02",
      allergies: ["Iodine"],
      vitalSigns: blankVitals,
      nyha_class_description: "",
      primary_diagnosis_text: "STEMI post-PCI",
      secondaryDiagnoses: ["Hyperlipidemia"],
      labs: [],
      medications: [],
      treatments: [],
      last_imaging_summary: "",
      last_ecg_summary: "",
    },
  },
  {
    name: "Sepsis – Pneumonia Source",
    description: "75-year-old female febrile, hypotensive with bilateral infiltrates.",
    data: {
      patient_full_name: "Paula Young",
      patient_age: "75",
      patient_gender: "Female",
      patient_mrn: "MED005",
      patient_dob: "1949-02-02",
      patient_insurance_plan: "Medicare",
      patient_policy_number: "MED-005",
      patient_primary_provider: "Dr. Allen",
      patient_admission_date: "2025-05-01",
      allergies: ["Penicillin"],
      vitalSigns: blankVitals,
      nyha_class_description: "",
      primary_diagnosis_text: "Sepsis – CAP source",
      secondaryDiagnoses: [],
      labs: [],
      medications: [],
      treatments: [],
      last_imaging_summary: "",
      last_ecg_summary: "",
    },
  },
  {
    name: "CKD Stage 4 – Anemia",
    description: "63-year-old male with CKD4 and symptomatic anemia.",
    data: {
      patient_full_name: "Quentin Brooks",
      patient_age: "63",
      patient_gender: "Male",
      patient_mrn: "MED006",
      patient_dob: "1962-08-21",
      patient_insurance_plan: "UHC",
      patient_policy_number: "MED-006",
      patient_primary_provider: "Dr. Malik",
      patient_admission_date: "2025-05-06",
      allergies: [],
      vitalSigns: blankVitals,
      nyha_class_description: "",
      primary_diagnosis_text: "CKD4 with anemia",
      secondaryDiagnoses: [],
      labs: [],
      medications: [],
      treatments: [],
      last_imaging_summary: "",
      last_ecg_summary: "",
    },
  },
  {
    name: "Ischemic Stroke – Rehab Phase",
    description: "70-year-old female day 3 post left MCA stroke.",
    data: {
      patient_full_name: "Rosa Delgado",
      patient_age: "70",
      patient_gender: "Female",
      patient_mrn: "MED007",
      patient_dob: "1954-10-15",
      patient_insurance_plan: "Medicare",
      patient_policy_number: "MED-007",
      patient_primary_provider: "Dr. O'Neil",
      patient_admission_date: "2025-05-04",
      allergies: [],
      vitalSigns: blankVitals,
      nyha_class_description: "",
      primary_diagnosis_text: "Left MCA ischemic stroke",
      secondaryDiagnoses: ["Aphasia"],
      labs: [],
      medications: [],
      treatments: [],
      last_imaging_summary: "",
      last_ecg_summary: "",
    },
  },
  {
    name: "Upper GI Bleed – Peptic Ulcer",
    description: "57-year-old male with hematemesis and melena.",
    data: {
      patient_full_name: "Steven White",
      patient_age: "57",
      patient_gender: "Male",
      patient_mrn: "MED008",
      patient_dob: "1967-01-09",
      patient_insurance_plan: "Cigna",
      patient_policy_number: "MED-008",
      patient_primary_provider: "Dr. Ford",
      patient_admission_date: "2025-05-06",
      allergies: ["NSAIDs"],
      vitalSigns: blankVitals,
      nyha_class_description: "",
      primary_diagnosis_text: "Upper GI bleed – PUD",
      secondaryDiagnoses: [],
      labs: [],
      medications: [],
      treatments: [],
      last_imaging_summary: "",
      last_ecg_summary: "",
    },
  },
  {
    name: "Asthma – Acute Exacerbation",
    description: "22-year-old female with wheezing after allergen exposure.",
    data: {
      patient_full_name: "Tara Cooper",
      patient_age: "22",
      patient_gender: "Female",
      patient_mrn: "MED009",
      patient_dob: "2003-02-28",
      patient_insurance_plan: "Student Plan",
      patient_policy_number: "MED-009",
      patient_primary_provider: "Dr. Wilson",
      patient_admission_date: "2025-05-05",
      allergies: ["Pollen"],
      vitalSigns: blankVitals,
      nyha_class_description: "",
      primary_diagnosis_text: "Asthma exacerbation",
      secondaryDiagnoses: [],
      labs: [],
      medications: [],
      treatments: [],
      last_imaging_summary: "",
      last_ecg_summary: "",
    },
  },
  {
    name: "Appendectomy – Post-Op Day 1",
    description: "18-year-old male POD#1 after laparoscopic appendectomy.",
    data: {
      patient_full_name: "Victor Wu",
      patient_age: "18",
      patient_gender: "Male",
      patient_mrn: "MED010",
      patient_dob: "2007-07-18",
      patient_insurance_plan: "Parents BCBS",
      patient_policy_number: "MED-010",
      patient_primary_provider: "Dr. Taylor",
      patient_admission_date: "2025-05-07",
      allergies: [],
      vitalSigns: blankVitals,
      nyha_class_description: "",
      primary_diagnosis_text: "Post-op care – appendectomy",
      secondaryDiagnoses: [],
      labs: [],
      medications: [],
      treatments: [],
      last_imaging_summary: "",
      last_ecg_summary: "",
    },
  },
];

export const SCENARIOS: PatientScenario[] = [...mentalHealth, ...medical];
